commonLabels:
  app: gitops
  version: "0.1"
  kustomize: "true"
  kind: toolbelt

resources:
- service-account.yaml
- role-binding.yaml
- deploymentk8s.yaml

configMapGenerator:
  - name: gitops-config
